### ISSUE TITLE
don't let players build ic

### ISSUE THREAD

**Issue by tank45210** [iwouldntdodh/CRH1v1#2]
make infra requirement for building ic 11 or increase cost

**Comment by iwouldntdodh** [comment]
I am concerned setting infra to 11 might introduce bugs, while increasing the cost to the point where it's not profitable is something I can't see have that effect. Probably should try and set at some sweet spot were AI nations that are scripted to build IC still will slowly get IC, but it won't ever be worth to do so neither player will do it. Additionally We don't want the USSR to build a massive amount of IC because then Germany will not be able to trade resources with them after a certain point.

**Comment by iwouldntdodh** [comment]
doubled the cost and time for a 4 times total cost increase.
